import { createElement, useCallback, useEffect, useState } from "react";
import { BarChart3, CalendarDays, Snowflake, Users, WalletCards } from "lucide-react";
import AdminErrorState from "../components/AdminErrorState";
import AdminStatusBadge from "../components/AdminStatusBadge";
import { adminReportsApi, getAdminApiError } from "../services/adminApi";
import { formatTHB, safeDate } from "../utils/formatters";

function inputDate(date) { return date.toISOString().slice(0, 10); }
function initialRange() { const to = new Date(); const from = new Date(to); from.setUTCDate(from.getUTCDate() - 29); return { dateFrom: inputDate(from), dateTo: inputDate(to) }; }
function apiRange(range) { return { dateFrom: `${range.dateFrom}T00:00:00.000Z`, dateTo: `${range.dateTo}T23:59:59.999Z` }; }
function Panel({ title, children, className = "" }) { return <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}><h2 className="border-b border-slate-100 px-5 py-4 font-semibold">{title}</h2><div className="p-5">{children}</div></section>; }
function Metric({ label, value, icon }) { return <div className="rounded-xl bg-slate-50 p-4">{createElement(icon, { size: 18, className: "text-cyan-700", "aria-hidden": true })}<p className="mt-3 text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-950">{value}</p></div>; }

function TrendBars({ data, valueKey = "count", format = String }) {
  if (!data?.length) return <p className="py-12 text-center text-sm text-slate-500">No trend data in this date range.</p>;
  const maximum = Math.max(...data.map((item) => Number(item[valueKey]) || 0), 1);
  return <div className="overflow-x-auto"><div className="flex h-52 min-w-[560px] items-end gap-2 border-b border-slate-200 pt-4" role="img" aria-label="Daily trend chart">{data.map((item) => <div key={item.date} className="group flex min-w-5 flex-1 flex-col items-center justify-end"><span className="mb-1 hidden text-[10px] text-slate-500 group-hover:block">{format(item[valueKey])}</span><div className="w-full max-w-8 rounded-t bg-gradient-to-t from-indigo-600 to-cyan-400" style={{ height: `${Math.max(3, ((Number(item[valueKey]) || 0) / maximum) * 150)}px` }} title={`${safeDate(item.date)}: ${format(item[valueKey])}`} /><span className="mt-2 -rotate-45 whitespace-nowrap text-[9px] text-slate-400">{new Date(item.date).toLocaleDateString("en-GB", { day: "2-digit", month: "short" })}</span></div>)}</div></div>;
}

export default function AdminReportsPage() {
  const [range, setRange] = useState(initialRange);
  const [appliedRange, setAppliedRange] = useState(initialRange);
  const [reports, setReports] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [rangeError, setRangeError] = useState("");
  const load = useCallback(async (signal) => { setLoading(true); setError(""); try { const params = apiRange(appliedRange); const [transactions, users, frozen, wallets] = await Promise.all([adminReportsApi.transactions(params, { signal }), adminReportsApi.users(params, { signal }), adminReportsApi.frozenAccounts({ ...params, limit: 10 }, { signal }), adminReportsApi.walletBalances({ signal })]); setReports({ transactions: transactions.data, users: users.data, frozen: frozen.data, wallets: wallets.data }); } catch (requestError) { if (requestError.code !== "ERR_CANCELED") setError(getAdminApiError(requestError, "Unable to load reports.")); } finally { if (!signal?.aborted) setLoading(false); } }, [appliedRange]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => load(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [load]);
  const apply = (event) => { event.preventDefault(); if (!range.dateFrom || !range.dateTo) return setRangeError("Select both dates."); if (range.dateFrom > range.dateTo) return setRangeError("Start date cannot be later than end date."); if ((new Date(range.dateTo) - new Date(range.dateFrom)) / 86400000 > 366) return setRangeError("Date range cannot exceed 366 days."); setRangeError(""); setAppliedRange(range); };
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700">Analytics</p><h1 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">Reports</h1><p className="mt-2 text-sm text-slate-500">Aggregated customer, transaction, frozen-account, and wallet insights.</p></div><form onSubmit={apply} className="flex flex-col gap-2 rounded-xl border border-slate-200 bg-white p-3 sm:flex-row sm:items-end"><label className="text-xs text-slate-600">From<input type="date" value={range.dateFrom} onChange={(event) => setRange({ ...range, dateFrom: event.target.value })} className="input input-sm input-bordered mt-1 block bg-white" /></label><label className="text-xs text-slate-600">To<input type="date" value={range.dateTo} max={inputDate(new Date())} onChange={(event) => setRange({ ...range, dateTo: event.target.value })} className="input input-sm input-bordered mt-1 block bg-white" /></label><button className="btn btn-sm border-0 bg-slate-900 text-white"><CalendarDays size={15} /> Apply</button></form></div>{rangeError && <p className="text-right text-sm text-rose-600" role="alert">{rangeError}</p>}
    {loading ? <div className="grid gap-4 md:grid-cols-2"><div className="h-72 animate-pulse rounded-2xl bg-slate-200" /><div className="h-72 animate-pulse rounded-2xl bg-slate-200" /></div> : error ? <AdminErrorState message={error} onRetry={() => load()} /> : reports && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Total users" value={(reports.users.summary.totalUsers ?? 0).toLocaleString()} /><Metric icon={BarChart3} label="Transactions" value={(reports.transactions.summary.transactionCount ?? 0).toLocaleString()} /><Metric icon={Snowflake} label="Frozen in range" value={(reports.frozen.total ?? 0).toLocaleString()} /><Metric icon={WalletCards} label="Total wallet balance" value={formatTHB(reports.wallets.summary.totalBalance ?? 0)} /></div>
      <div className="grid gap-6 xl:grid-cols-2"><Panel title="User-registration trend"><TrendBars data={reports.users.registrations} /></Panel><Panel title="Transaction-volume trend"><TrendBars data={reports.transactions.trend} valueKey="volume" format={formatTHB} /></Panel></div>
      <div className="grid gap-6 xl:grid-cols-2"><Panel title="Transaction summary"><div className="grid grid-cols-2 gap-3"><Metric icon={BarChart3} label="Total volume" value={formatTHB(reports.transactions.summary.totalVolume ?? 0)} /><Metric icon={BarChart3} label="Successful volume" value={formatTHB(reports.transactions.summary.successfulVolume ?? 0)} /></div><div className="mt-5 overflow-x-auto"><table className="table table-sm"><thead><tr><th>Status</th><th>Count</th><th>Volume</th></tr></thead><tbody>{reports.transactions.byStatus.map((item) => <tr key={item._id}><td><AdminStatusBadge status={item._id} /></td><td>{item.count.toLocaleString()}</td><td>{formatTHB(item.volume ?? 0)}</td></tr>)}</tbody></table></div></Panel><Panel title="Wallet-balance summary"><dl className="grid grid-cols-2 gap-4"><div><dt className="text-xs text-slate-500">Wallets</dt><dd className="text-xl font-bold">{reports.wallets.summary.walletCount.toLocaleString()}</dd></div><div><dt className="text-xs text-slate-500">Average balance</dt><dd className="text-xl font-bold">{formatTHB(reports.wallets.summary.averageBalance ?? 0)}</dd></div><div><dt className="text-xs text-slate-500">Minimum</dt><dd className="font-semibold">{formatTHB(reports.wallets.summary.minimumBalance ?? 0)}</dd></div><div><dt className="text-xs text-slate-500">Maximum</dt><dd className="font-semibold">{formatTHB(reports.wallets.summary.maximumBalance ?? 0)}</dd></div></dl><div className="mt-5 overflow-x-auto"><table className="table table-sm"><thead><tr><th>Status</th><th>Wallets</th><th>Balance</th></tr></thead><tbody>{reports.wallets.byStatus.map((item) => <tr key={item._id}><td><AdminStatusBadge status={item._id} /></td><td>{item.walletCount}</td><td>{formatTHB(item.totalBalance ?? 0)}</td></tr>)}</tbody></table></div></Panel></div>
      <Panel title="Frozen-account summary">{!reports.frozen.accounts.length ? <p className="py-8 text-center text-sm text-slate-500">No accounts were frozen in this range.</p> : <div className="overflow-x-auto"><table className="table"><thead><tr><th>User</th><th>Status</th><th>Balance</th><th>Reason</th><th>Frozen</th></tr></thead><tbody>{reports.frozen.accounts.map((user) => <tr key={user._id}><td><p className="font-medium">{user.fullName}</p><p className="text-xs text-slate-500">{user.email}</p></td><td><AdminStatusBadge status={user.accountStatus} /></td><td>{formatTHB(user.balance ?? 0)}</td><td>{user.frozenReason || "—"}</td><td className="whitespace-nowrap text-xs">{safeDate(user.frozenAt)}</td></tr>)}</tbody></table></div>}</Panel></>}
  </div>;
}
