import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, ReceiptText, UserRound } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import AdminErrorState from "../components/AdminErrorState";
import AdminStatusBadge from "../components/AdminStatusBadge";
import { adminTransactionsApi, getAdminApiError } from "../services/adminApi";
import { formatTHB, partyName, safeDate } from "../utils/formatters";

function Panel({ title, children, className = "" }) { return <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}><h2 className="border-b border-slate-100 px-5 py-4 font-semibold">{title}</h2><div className="p-5">{children}</div></section>; }
function Item({ label, value }) { return <div><dt className="text-xs uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 break-words text-sm font-medium text-slate-800">{value ?? "—"}</dd></div>; }

export default function AdminTransactionDetailsPage() {
  const { transactionId } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const loadTransaction = useCallback(async (signal) => { setLoading(true); setError(""); try { const response = await adminTransactionsApi.getById(transactionId, { signal }); setData(response.data); } catch (requestError) { if (requestError.code !== "ERR_CANCELED") setError(getAdminApiError(requestError, "Unable to load transaction.")); } finally { if (!signal?.aborted) setLoading(false); } }, [transactionId]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => loadTransaction(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [loadTransaction]);
  if (loading && !data) return <div className="h-80 animate-pulse rounded-2xl bg-slate-200" role="status"><span className="sr-only">Loading transaction…</span></div>;
  if (error && !data) return <AdminErrorState message={error} onRetry={() => loadTransaction()} />;
  const { transaction, ledgerEntries = [] } = data;
  const failed = transaction.status === "FAILED";
  return <div className="space-y-6"><div><Link to="/admin/transactions" className="inline-flex items-center gap-1 text-sm font-medium text-cyan-700"><ArrowLeft size={16} /> Back to transactions</Link><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700">Transaction details</p><h1 className="mt-1 break-all font-mono text-xl font-bold text-slate-950">{transaction.reference || transaction.transactionId}</h1></div><AdminStatusBadge status={transaction.status} /></div></div>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="General information"><dl className="grid gap-5 sm:grid-cols-2"><Item label="Transaction ID" value={transaction.transactionId} /><Item label="Reference" value={transaction.reference} /><Item label="Type" value={transaction.type} /><Item label="Created" value={safeDate(transaction.createdAt)} /><Item label="Updated" value={safeDate(transaction.updatedAt)} /><Item label="Performed by" value={transaction.performedBy?.name ?? (transaction.type === "TRANSFER" ? "Customer" : "System administrator")} /></dl></Panel><Panel title="Amount and fees"><div className="rounded-xl bg-slate-950 p-5 text-white"><p className="text-xs text-slate-400">Transaction amount</p><p className="mt-2 text-3xl font-bold">{formatTHB(transaction.amount ?? 0)}</p></div><div className="mt-4 flex justify-between text-sm"><span className="text-slate-500">Fee</span><strong>{formatTHB(transaction.fee ?? 0)}</strong></div></Panel>
      <Panel title="Sender and receiver"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><UserRound size={19} className="text-slate-400" /><p className="mt-3 text-xs text-slate-500">Sender</p><p className="font-semibold">{partyName(transaction.sender)}</p><p className="font-mono text-xs text-slate-500">{transaction.sender?.accountNumber ?? "System"}</p>{transaction.sender?._id && <Link to={`/admin/users/${transaction.sender._id}`} className="mt-2 inline-block text-xs font-medium text-cyan-700">View user</Link>}</div><div className="rounded-xl bg-slate-50 p-4"><UserRound size={19} className="text-slate-400" /><p className="mt-3 text-xs text-slate-500">Receiver</p><p className="font-semibold">{partyName(transaction.receiver)}</p><p className="font-mono text-xs text-slate-500">{transaction.receiver?.accountNumber ?? "System"}</p>{transaction.receiver?._id && <Link to={`/admin/users/${transaction.receiver._id}`} className="mt-2 inline-block text-xs font-medium text-cyan-700">View user</Link>}</div></div></Panel><Panel title="Status timeline"><ol className="space-y-5 border-l border-slate-200 pl-5"><li className="relative"><Clock3 className="absolute -left-[31px] top-0 bg-white text-cyan-700" size={20} /><p className="text-sm font-medium">Transaction created</p><p className="text-xs text-slate-500">{safeDate(transaction.createdAt)}</p></li><li className="relative">{failed ? <AlertTriangle className="absolute -left-[31px] top-0 bg-white text-rose-600" size={20} /> : <CheckCircle2 className="absolute -left-[31px] top-0 bg-white text-emerald-600" size={20} />}<p className="text-sm font-medium">Status: {transaction.status}</p><p className="text-xs text-slate-500">{safeDate(transaction.updatedAt || transaction.createdAt)}</p></li></ol></Panel>
    </div>
    {failed && <Panel title="Failure information"><div className="flex gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-800"><AlertTriangle className="shrink-0" size={20} /><div><p className="font-semibold">Transaction failed</p><p className="mt-1 text-sm">{transaction.reason || transaction.note || "No failure reason was recorded."}</p></div></div></Panel>}
    <Panel title="Related ledger entries and balance changes">{!ledgerEntries.length ? <div className="py-8 text-center"><ReceiptText className="mx-auto text-slate-300" size={30} /><p className="mt-2 text-sm text-slate-500">No ledger entries are associated with this transaction.</p></div> : <div className="overflow-x-auto"><table className="table"><thead><tr><th>Wallet owner</th><th>Entry</th><th>Amount</th><th>Balance before</th><th>Balance after</th><th>Change</th><th>Date</th></tr></thead><tbody>{ledgerEntries.map((entry) => <tr key={entry._id}><td><p className="font-medium">{partyName(entry.userId, "Unknown wallet")}</p><p className="font-mono text-xs text-slate-500">{entry.userId?.accountNumber}</p></td><td><AdminStatusBadge status={entry.type} /></td><td className="font-semibold">{formatTHB(entry.amount ?? 0)}</td><td>{formatTHB(entry.balanceBefore ?? 0)}</td><td>{formatTHB(entry.balanceAfter ?? 0)}</td><td className={entry.type === "CREDIT" ? "text-emerald-700" : "text-rose-700"}>{entry.type === "CREDIT" ? "+" : "−"}{formatTHB(entry.amount ?? 0)}</td><td className="whitespace-nowrap text-xs">{safeDate(entry.createdAt)}</td></tr>)}</tbody></table></div>}</Panel>
  </div>;
}
