import { useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Eye, FileClock, Search, X } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import AdminErrorState from "../components/AdminErrorState";
import { useAdminModalKeyboard } from "../hooks/useAdminModalKeyboard";
import { adminAuditLogsApi, getAdminApiError } from "../services/adminApi";
import { safeDate } from "../utils/formatters";

const ACTIONS = ["ADMIN_LOGIN_SUCCESS", "ADMIN_LOGIN_FAILED", "ADMIN_LOGOUT", "ADMIN_PASSWORD_CHANGED", "USER_FROZEN", "USER_UNFROZEN", "USER_SESSIONS_REVOKED", "BALANCE_CREDIT_ADJUSTMENT", "BALANCE_DEBIT_ADJUSTMENT", "SYSTEM_SETTINGS_UPDATED"];
const ENTITIES = ["User", "Transaction", "SystemSettings", "Admin"];
function filtersFrom(params) { return { action: params.get("action") ?? "", entityType: params.get("entityType") ?? "", entityId: params.get("entityId") ?? "", dateFrom: params.get("dateFrom")?.slice(0, 10) ?? "", dateTo: params.get("dateTo")?.slice(0, 10) ?? "" }; }
function JsonBlock({ value }) { return <pre className="max-h-72 overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-5 text-slate-200">{value ? JSON.stringify(value, null, 2) : "No values recorded."}</pre>; }

function DetailsDialog({ log, onClose }) {
  useAdminModalKeyboard("audit-details-title", onClose);
  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/70 p-4"><div role="dialog" aria-modal="true" aria-labelledby="audit-details-title" className="my-4 w-full max-w-3xl rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-slate-100 p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-cyan-700">Read-only audit record</p><h2 id="audit-details-title" className="mt-1 text-xl font-bold">{log.action}</h2><p className="mt-1 text-xs text-slate-500">{safeDate(log.createdAt)}</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Close audit details"><X size={20} /></button></header><div className="space-y-5 p-5"><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Administrator</dt><dd className="font-medium">{log.adminId?.name ?? "Unknown admin"}</dd><dd className="text-xs text-slate-500">{log.adminId?.email}</dd></div><div><dt className="text-xs text-slate-500">Target</dt><dd className="font-medium">{log.entityType || "—"}</dd><dd className="break-all font-mono text-xs text-slate-500">{log.entityId || "—"}</dd></div><div><dt className="text-xs text-slate-500">Reason</dt><dd className="text-sm">{log.reason || "No reason recorded."}</dd></div><div><dt className="text-xs text-slate-500">Request source</dt><dd className="font-mono text-xs">{log.ipAddress || "—"}</dd><dd className="mt-1 break-all text-xs text-slate-500">{log.userAgent || "—"}</dd></div></dl><div className="grid gap-4 lg:grid-cols-2"><div><h3 className="mb-2 text-sm font-semibold">Previous values</h3><JsonBlock value={log.previousData} /></div><div><h3 className="mb-2 text-sm font-semibold">New values</h3><JsonBlock value={log.newData} /></div></div><p className="rounded-lg bg-slate-50 p-3 text-xs text-slate-500">Audit records are immutable and cannot be edited or deleted from this portal.</p></div></div></div>;
}

export default function AdminAuditLogsPage() {
  const [params, setParams] = useSearchParams();
  const [filters, setFilters] = useState(() => filtersFrom(params));
  const [result, setResult] = useState({ logs: [], total: 0, totalPages: 0, page: 1 });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [filterError, setFilterError] = useState("");
  const [selected, setSelected] = useState(null);
  const load = useCallback(async (signal) => { setLoading(true); setError(""); try { const response = await adminAuditLogsApi.list(Object.fromEntries(params), { signal }); setResult(response.data); } catch (requestError) { if (requestError.code !== "ERR_CANCELED") setError(getAdminApiError(requestError, "Unable to load audit logs.")); } finally { if (!signal?.aborted) setLoading(false); } }, [params]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => load(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [load]);
  useEffect(() => { const timer = window.setTimeout(() => setFilters(filtersFrom(params)), 0); return () => window.clearTimeout(timer); }, [params]);
  const apply = (event) => { event.preventDefault(); if (filters.entityId && !/^[a-f\d]{24}$/i.test(filters.entityId)) return setFilterError("Entity ID must be a valid 24-character ObjectId."); if (filters.dateFrom && filters.dateTo && filters.dateFrom > filters.dateTo) return setFilterError("Start date cannot be later than end date."); setFilterError(""); const next = {}; for (const [key, value] of Object.entries(filters)) if (value) next[key] = key === "dateFrom" ? `${value}T00:00:00.000Z` : key === "dateTo" ? `${value}T23:59:59.999Z` : value; next.page = "1"; setParams(next); };
  const page = (number) => { const next = new URLSearchParams(params); next.set("page", number); setParams(next); };
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700">Analytics</p><h1 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">Audit Logs</h1><p className="mt-2 text-sm text-slate-500">Read-only history of sensitive administrator actions.</p></div><form onSubmit={apply} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><select aria-label="Audit action" value={filters.action} onChange={(event) => setFilters({ ...filters, action: event.target.value })} className="select select-bordered w-full bg-white"><option value="">All actions</option>{ACTIONS.map((action) => <option key={action}>{action}</option>)}</select><select aria-label="Entity type" value={filters.entityType} onChange={(event) => setFilters({ ...filters, entityType: event.target.value })} className="select select-bordered w-full bg-white"><option value="">All entity types</option>{ENTITIES.map((entity) => <option key={entity}>{entity}</option>)}</select><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><span className="sr-only">Entity ID</span><input value={filters.entityId} onChange={(event) => setFilters({ ...filters, entityId: event.target.value.trim() })} className="input input-bordered w-full bg-white pl-9 font-mono text-xs" placeholder="Target ObjectId" /></label><label><span className="sr-only">Date from</span><input type="date" value={filters.dateFrom} onChange={(event) => setFilters({ ...filters, dateFrom: event.target.value })} className="input input-bordered w-full bg-white" /></label><label><span className="sr-only">Date to</span><input type="date" value={filters.dateTo} onChange={(event) => setFilters({ ...filters, dateTo: event.target.value })} className="input input-bordered w-full bg-white" /></label></div><div className="mt-3 flex items-center justify-between"><p className="text-sm text-rose-600" role="alert">{filterError}</p><button className="btn btn-sm border-0 bg-slate-900 text-white">Apply filters</button></div></form>
    {loading ? <div className="space-y-3">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-16 animate-pulse rounded-xl bg-slate-200" />)}</div> : error ? <AdminErrorState message={error} onRetry={() => load()} /> : <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex justify-between border-b border-slate-100 px-5 py-4 text-sm"><span>{result.total.toLocaleString()} audit records</span><span>Page {result.page} of {Math.max(result.totalPages, 1)}</span></div>{!result.logs.length ? <div className="p-12 text-center"><FileClock className="mx-auto text-slate-300" size={34} /><p className="mt-3 text-sm text-slate-500">No audit logs match these filters.</p></div> : <div className="overflow-x-auto"><table className="table"><thead><tr><th>Admin action</th><th>Administrator</th><th>Target</th><th>Reason</th><th>Date and time</th><th>IP address</th><th /></tr></thead><tbody>{result.logs.map((log) => <tr key={log._id}><td className="text-xs font-semibold">{log.action}</td><td><p className="text-sm font-medium">{log.adminId?.name ?? "Unknown"}</p><p className="text-xs text-slate-500">{log.adminId?.email}</p></td><td><p className="text-sm">{log.entityType || "—"}</p><p className="max-w-32 truncate font-mono text-[10px] text-slate-500">{log.entityId || "—"}</p></td><td className="max-w-52 truncate text-sm">{log.reason || "—"}</td><td className="whitespace-nowrap text-xs">{safeDate(log.createdAt)}</td><td className="font-mono text-xs">{log.ipAddress || "—"}</td><td><button onClick={() => setSelected(log)} className="btn btn-ghost btn-sm text-cyan-700"><Eye size={15} /> Details</button></td></tr>)}</tbody></table></div>}<div className="flex justify-between border-t border-slate-100 p-4"><button disabled={result.page <= 1} onClick={() => page(result.page - 1)} className="btn btn-sm bg-white"><ChevronLeft size={16} /> Previous</button><button disabled={result.page >= result.totalPages} onClick={() => page(result.page + 1)} className="btn btn-sm bg-white">Next <ChevronRight size={16} /></button></div></section>}{selected && <DetailsDialog log={selected} onClose={() => setSelected(null)} />}
  </div>;
}
